// Auto-generated by the postman-to-k6 converter

import "./../libs/shim/core.js";
import "./../libs/shim/expect.js";
import "./../libs/shim/urijs.js";
import { Httpx ,Get,URLSearchParams,URL} from 'https://jslib.k6.io/httpx/0.0.1/index.js';
import { describe } from 'https://jslib.k6.io/expect/0.0.4/index.js';


export let options = {
  // rps: 500,
  maxRedirects: 0,
  discardResponseBodies: false,
  throw: true,
  noCookiesReset: true,
  noConnectionReuse: false,
  duration: '1m',
  vus: 50,
};

const session = new Httpx(
    { 
        baseURL: 'https://hyphen-v2-api.biconomy.io' 
    }
);

export default function sanityPerfTestSuite() {
    describe('Get APIs ', (t) => {
       
        const responses = session.batch(
          [
            new Get('/api/v1/configuration/tokens'),
            new Get('/api/v1/admin/supported-token/list?networkId=1'),  
          ],
          {
            tags: { name: 'GetPoolInfo' },
          }
        );
    // CHECKS
        responses.forEach((response) => {
          t.expect(response.status)
            .as('Response status').toEqual(200)
            .and(response).toHaveValidJson()
            .and(response.timings.duration).toBeLessThan(5000);
        });
      });
    

}
